these
  primaryColor="#e74c3c"                # Rojo primario
  backgroundColor="#ecf0f1"            # Color de fondo gris claro
  secondaryBackgroundColor="#7f8c8d"    # Color de fondo gris oscuro
  textColor="#2c3e50"                   # Color del texto
  font="Montserrat, sans-serif"         # Familia de fuentes
